boostcampwm-2021/WEB29-BoostTeams

- frontend/.eslintrc.js
- frontend/.prettierrc
- frontend/src/components/Header/index.tsx
- frontend/src/components/Login/index.tsx
- frontend/src/components/Sidebar/index.tsx
- frontend/src/routes/router.tsx
jsx에 Single Quote Rule을 추가하고 Rule에 어긋나는 파일들을 수정했습니다.
> jsxSingleQuote Rule 추가

- frontend/src/components/Calendar/CalendarHeader/index.tsx
- frontend/src/components/Calendar/CalendarHeader/style.ts
- frontend/src/components/Calendar/MonthlyCalendar/MonthContent/index.tsx
- frontend/src/components/Calendar/MonthlyCalendar/MonthContent/style.ts
- frontend/src/components/Calendar/MonthlyCalendar/MonthHeader/index.tsx
- frontend/src/components/Calendar/MonthlyCalendar/MonthHeader/style.ts
- frontend/src/components/Calendar/MonthlyCalendar/index.tsx
- frontend/src/components/Calendar/MonthlyCalendar/style.ts
- frontend/src/components/Calendar/dataStructure.ts
- frontend/src/templates/CalendarTemplate/index.tsx
- frontend/src/utils/constants.ts
> [Feat] 월간 달력 일정 표시, 토글 버튼

- frontend/package.json
- frontend/src/components/Calendar/WeeklyCalendar/Schedule/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/Schedule/style.ts
- frontend/src/components/Calendar/WeeklyCalendar/ScheduleItem/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/ScheduleItem/style.ts
- frontend/src/components/Calendar/WeeklyCalendar/WeekHeader/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/WeekHeader/style.ts
- frontend/src/templates/CalendarTemplate/index.tsx
- frontend/yarn.lock
> 주간 달력 일정 표시

- frontend/src/pages/LoginPage/index.tsx
- frontend/src/routes/PrivateRoute.tsx
- frontend/src/routes/router.tsx
> [Fix] Conflict resolve 이후 오류 해결

- backend/src/passport/local-strategy.ts
- backend/src/services/user-service.ts
- frontend/src/App.tsx
- frontend/src/apis/auth.ts
- frontend/src/utils/fetch.ts
> [Fix] Frontend dotenv 수정

- backend/src/passport/local-strategy.ts
- backend/src/services/user-service.ts
> [Fix] dotenv 환경 변수 BE 설정

- backend/src/services/user-service.ts
> [로그인] hotfix

- frontend/.eslintrc.js
- frontend/src/apis/schedule.ts
- frontend/src/components/Calendar/CalendarModal/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/WeekContent/index.tsx
- frontend/src/components/Calendar/dataStructure.ts
- frontend/src/components/Team/CardList/index.tsx
- frontend/src/components/Team/TeamCard/index.tsx
- frontend/src/components/common/Modal/index.tsx
> [Style] eslint rule 변경(camelcase)

- backend/src/controllers/user-controller.ts
- backend/src/routes/user-router.ts
- backend/src/services/user-service.ts
- frontend/src/apis/user.ts
- frontend/src/components/common/Header/ProfileSimple/UpdateModal/index.tsx
- frontend/src/components/common/Header/ProfileSimple/UpdateModal/style.ts
- frontend/src/components/common/Header/ProfileSimple/UserInfo/index.tsx
- frontend/src/components/common/Header/ProfileSimple/UserInfo/style.ts
- frontend/src/components/common/Header/ProfileSimple/index.tsx
- frontend/src/components/common/Header/index.tsx
- frontend/src/components/common/Icons/ProfileIcon/style.ts
- frontend/src/utils/fetch.ts
- 노션 가이드 보고 재사용했습니다! 멋진 컴포넌트 감사합니다 ㅎㅎ
- PATCH /api/user/name 추가했습니다. 노션 API 명세서에 추가했어요!
> [로그인] 사용자 이름 변경

- backend/src/index.ts
놀랍게도 userRouter가 주석처리가 되어있었습니다..? (이름 변경에 쓰임)
> [Chore] userRouter 주석 해제

- backend/src/controllers/schedule-controller.ts
- frontend/src/components/Calendar/CalendarModal/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/WeekContent/index.tsx
- frontend/src/pages/CalendarPage/index.tsx
- frontend/src/routes/router.tsx
- frontend/src/templates/CalendarTemplate/index.tsx
url params의 팀 id에 따라 일정을 fetch하여 가져오도록 하였습니다.
Co-authored-by: Kang Minji <mminjg@users.noreply.github.com>
> [Feat] 팀 일정 마무리

- backend/src/entities/team-user.ts
> [Fix] team user entity state 다시 추가

- frontend/src/components/common/Navbar/index.tsx
- frontend/src/components/common/Navbar/style.ts
> [Feat] navbar 라우팅, 팀 아이콘 동적 생성

- backend/src/services/team-service.ts
- backend/src/services/team-user-service.ts
- frontend/src/apis/team.ts
- frontend/src/components/Team/Cards/InviteCard.tsx
- frontend/src/components/Team/CreateTeamModal/index.tsx
- frontend/src/components/Team/CreateTeamModal/style.ts
- frontend/src/utils/fetch.ts
> [팀 관리] 팀 생성

- frontend/src/App.tsx
- frontend/src/components/common/Navbar/index.tsx
- frontend/src/pages/TeamPage/index.tsx
- frontend/src/templates/CalendarTemplate/index.tsx
> [Fix] navbar 팀 리스트 더미 데이터를 실제 팀 목록으로 변경

- backend/src/controllers/schedule-controller.ts
- backend/src/controllers/team-contorller.ts
- backend/src/controllers/user-controller.ts
- 불필요한 Response message 제거
- RESTful하게 status code 수정
> [Refactor] BE REST API status code 수정

- backend/src/controllers/schedule-controller.ts
- backend/src/controllers/user-controller.ts
- backend/src/passport/local-strategy.ts
- frontend/src/apis/auth.ts
- frontend/src/apis/user.ts
- 단순히 Response 전송 방법, status Code만 바꿔주면 될 줄 알았는데, 그게 아니더라구요....
> [Fix] Toast Message 에러 수정

- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/package.json
- frontend/src/components/common/Button/index.stories.tsx
- frontend/src/components/common/Button/index.tsx
- frontend/src/components/common/ColorPicker/index.stories.tsx
- frontend/src/components/common/ColorPicker/index.tsx
- frontend/src/components/common/Header/ProfileSimple/index.stories.tsx
- frontend/yarn.lock
> [chore/storybook#78] 스토리북 초기 설정

- backend/src/services/schedule-service.ts
- frontend/src/apis/schedule.ts
- frontend/src/components/Calendar/CalendarModal/index.tsx
- frontend/src/components/Calendar/CalendarModal/style.ts
- frontend/src/components/Calendar/MonthlyCalendar/MonthContent/style.ts
- frontend/src/components/Calendar/WeeklyCalendar/ScheduleItem/index.tsx
- frontend/src/components/Calendar/WeeklyCalendar/index.tsx
- frontend/src/components/common/Button/index.tsx
- frontend/src/components/common/ColorPicker/index.tsx
- frontend/src/components/common/DropDown/index.tsx
- frontend/src/components/common/Modal/index.tsx
- frontend/src/components/common/Navbar/index.tsx
- frontend/src/pages/CalendarPage/index.tsx
- frontend/src/templates/CalendarTemplate/index.tsx
- frontend/src/utils/calendar.ts
> [Refactor/calendar#59] 일정 리팩토링, 경고 처리

- frontend/src/components/Users/UserList/UserList.tsx
> [Fix] import 오류 수정

- backend/src/services/team-user-service.ts
팀 생성 쿼리 수정
- team_user table에 `role` 컬럼이 생김에 따라, 쿼리도 수정했습니다.
> [Fix] 팀 생성 쿼리 수정

- backend/src/sockets/index.ts
- backend/src/sockets/team.ts
- backend/src/sockets/teamBoard.ts
- frontend/src/components/Board/Canvas/index.tsx
- frontend/src/components/Board/CreateButton/index.tsx
- frontend/src/components/Board/CreateButton/style.ts
- frontend/src/components/Board/Modal/index.tsx
- frontend/src/components/Board/Modal/style.ts
- frontend/src/components/Board/Postit/index.tsx
- frontend/src/pages/BoardPage/index.tsx
- frontend/src/templates/BoardTemplate/index.tsx
- frontend/src/utils/constants.ts
> [팀 보드] 팀 보드 page UI 구성, Socket API 구성

- backend/src/controllers/team-contorller.ts
- backend/src/routes/team-router.ts
- backend/src/services/team-user-service.ts
- frontend/src/apis/team.ts
- frontend/src/components/Users/DeleteTeamModal/style.ts
- frontend/src/components/Users/ExitTeamModal/style.ts
- frontend/src/components/Users/Modal/DeleteTeamModal/index.tsx
- frontend/src/components/Users/Modal/ExitTeamModal/index.tsx
- frontend/src/components/Users/Modal/InviteUserModal/index.tsx
- frontend/src/components/Users/Modal/KickoutTeamModal/index.tsx
- frontend/src/components/Users/Modal/UpdateTeamModal/index.tsx
- frontend/src/components/Users/Modal/index.ts
- frontend/src/components/Users/Modal/style.ts
- frontend/src/components/Users/UserList/SearchUsers.tsx
- frontend/src/components/Users/UserList/User.tsx
- frontend/src/components/Users/UserList/UserList.tsx
- frontend/src/components/Users/UserList/index.tsx
- frontend/src/components/Users/UserList/style.ts
- frontend/src/components/Users/UsersHeader/style.ts
- frontend/src/components/common/Header/index.tsx
- frontend/src/components/common/Icons/ProfileIcon/index.tsx
- frontend/src/components/common/Navbar/index.tsx
- frontend/src/components/common/Navbar/style.ts
- frontend/src/components/common/index.ts
- frontend/src/pages/UsersPage/index.tsx
- frontend/src/stores/team.ts
- frontend/src/templates/UsersTemplate/index.tsx
- frontend/src/templates/UsersTemplate/style.ts
- frontend/src/utils/constants.ts
> [Feat/users#107#108] 팀 내부 관리 작업

- backend/src/sockets/team.ts
- backend/src/sockets/teamBoard.ts
- frontend/src/apis/team.ts
- frontend/src/components/common/Header/index.tsx
> 콘솔로그 제거 및 유저 상태 표기 변경

- backend/src/sockets/teamBoard.ts
> [Fix] 포스트잇 하나도 없을 때 생성 안되는 오류

- frontend/src/routes/TeamRoute.tsx
> [Fix] Socket polling 그만

- backend/src/index.ts
- frontend/src/routes/TeamRoute.tsx
> [Fix] Socket url 변경

- README.md
- backend/README.md
- frontend/README.md
> [Docs] README 수정

- frontend/src/components/Chat/ChatHeader/SearchHeader.tsx
- frontend/src/pages/UsersPage/index.tsx
- frontend/src/stores/team.ts
> [Fix] pr 머지 후 import 에러, 타입 에러 수정

- backend/src/redis/index.ts
- backend/src/sockets/teamBoard.ts
- backend/yarn.lock
- frontend/src/pages/BoardPage/index.tsx
1. 팀 보드 FE, BE를 연동했습니다
2. socket API의 파라미터 형식을 통일했습니다.
> [Fix] 팀 보드 FE,BE 연동, socket API 파라미터 형식 수정

- frontend/src/apis/team.ts
- frontend/src/components/Users/UserList/User.tsx
> [Fix] pr 머지시 삭제된 코드 추가

- backend/src/controllers/team-contorller.ts
- backend/src/entities/chat_room-user.ts
- backend/src/entities/chat_room.ts
- backend/src/routes/team-router.ts
- backend/src/services/team-user-service.ts
- frontend/package.json
- frontend/src/apis/team.ts
- frontend/src/components/Users/Modal/DeleteTeamModal/index.tsx
- frontend/src/components/Users/Modal/ExitTeamModal/index.tsx
- frontend/src/components/Users/Modal/KickoutTeamModal/index.tsx
- frontend/src/components/Users/Modal/UpdateTeamModal/index.tsx
- frontend/src/components/Users/UserList/SearchUsers.tsx
- frontend/src/components/Users/UserList/User.tsx
- frontend/src/components/Users/UserList/UserList.tsx
- frontend/src/components/Users/UserList/index.tsx
- frontend/src/components/Users/UsersHeader/index.tsx
- frontend/src/components/common/DropDown/index.tsx
- frontend/src/components/common/DropDown/style.ts
- frontend/src/pages/UsersPage/index.tsx
- frontend/src/stores/team.ts
- frontend/src/templates/UsersTemplate/index.tsx
- frontend/src/utils/constants.ts
- frontend/yarn.lock
- cascade on delete.. 엔티티에 이미 되어있는데 왜 삭제가 안될까요
> [팀 내부관리] 유저 권한 변경, 팀관리메뉴 드롭다운으로 변경, 리팩토링

- backend/src/sockets/teamBoard.ts
- frontend/src/components/Board/Canvas/index.tsx
- frontend/src/components/Board/CreateButton/index.tsx
- frontend/src/components/Board/CreateButton/style.ts
- frontend/src/components/Board/Postit/index.tsx
- frontend/src/components/common/Header/style.ts
- frontend/src/components/common/Navbar/style.ts
- frontend/src/pages/BoardPage/index.tsx
- frontend/src/routes/TeamRoute.tsx
- frontend/src/templates/BoardTemplate/index.tsx
- frontend/src/utils/constants.ts
작업 내용과 같습니다!
- 화면 크기가 달라도 상대적으로 위치하게 됩니다.
- 포스트잇 크기는 따로 조정하지 않았기 때문에 완벽하게 안잘리지는 않습니다.
- 드래그 중인 포스트잇은 살짝 크기가 다릅니다 (개선 요망..)
> [팀 보드] 일부 오류 수정 및 일부 개선

- backend/src/redis/index.ts
새로운 field 생성시 Index초기화 현상 수정
- 기존 : 새로운 field 생성시, index를 초기화 했습니다
- 개선 : index field가 존재하면, 새로 field를 초기화 하지 않도록 했습니다.
> [Fix]새로운 field 생성시 Index초기화 현상 수정

- backend/src/controllers/team-contorller.ts
- backend/src/controllers/user-controller.ts
- backend/src/index.ts
- backend/src/middlewares/user.ts
- backend/src/routes/schedule-router.ts
- backend/src/routes/team-router.ts
- backend/src/routes/user-router.ts
- backend/src/services/team-service.ts
- backend/src/services/team-user-service.ts
- frontend/src/apis/chat.ts
- frontend/src/apis/schedule.ts
- frontend/src/apis/team.ts
- frontend/src/apis/user.ts
- frontend/src/components/Users/Modal/UpdateTeamModal/index.tsx
- frontend/src/components/common/Header/ProfileSimple/index.tsx
team, user에 대해 변경하였습니다.
유저가 팀에 소속되어 있는지와 같은 검사를 여러개 하게되면 (ex 팀이 존재하는지 확인 - 팀에 소속되었는지 확인 - 같은 이름이 있는지 확인 - 실제 실행) 성능이 엄청 안좋아지지 않을까 싶은데 어떻게 해야될까요?
> [Fix] REST API path 변경

- backend/src/sockets/chat.ts
> [Fix] 콘솔로그 제거, 소켓 오류 해결

- backend/src/middlewares/user.ts
> [Fix] middleware error fix

- backend/src/routes/schedule-router.ts
- frontend/src/components/Users/Modal/DeleteTeamModal/index.tsx
- frontend/src/components/Users/Modal/ExitTeamModal/index.tsx
> [Fix] middleware error: 달력 인증

- backend/src/sockets/chat.ts
- frontend/src/components/Chat/ChatContent/Message/index.tsx
채팅방 썸네일 색 수정, 초대시 event 안가는 오류 수정
> [Fix] 채팅방 썸네일 색 수정, 초대시 event 안가는 오류 수정

- backend/src/middlewares/user.ts
- backend/src/routes/team-router.ts
> [Fix] middleware detach

- README.md
- backend/README.md
> [Docs] 5주차 README 업데이트

- backend/src/sockets/chat.ts
- backend/src/sockets/eventType.ts
- backend/src/sockets/team.ts
- backend/src/sockets/teamBoard.ts
string -> 상수로 묶음
일단은 단순히 string을 상수로 전환하는 작업만 진행했습니다.
+ chat의 socket도 상수처리를 진행했다가 revert로 취소했습니다.
> [Refactor] BE socket Event 상수 처리

- backend/ormconfig.ts
- backend/src/controllers/user-controller.ts
- backend/src/entities/user.ts
- backend/src/middlewares/token.ts
- backend/src/routes/auth-router.ts
- backend/src/services/user-service.ts
- frontend/src/apis/auth.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/SignUpPage/index.tsx
- frontend/src/routes/PrivateRoute.tsx
- frontend/src/routes/PublicRoute.tsx
- frontend/src/utils/fetch.ts
access token의 유효기간을 짧게 잡고 만료되면 refresh token으로 다시
받아오게 구현했습니다.
* .env 수정 필요합니다.
로그아웃을 했다가 다시 로그인을 하면 전 팀 목록이 유지되는데 트리거를 써야하겠죠..?
> [Feat] login refresh token 도입

- backend/package.json
- frontend/src/pages/LoginPage/index.tsx
> fix/token & script

- backend/.eslintrc
- backend/babel.config.js
- backend/jest.config.ts
- backend/package.json
- backend/src/index.ts
- backend/test/jest/auth.test.js
- backend/tsconfig.json
- backend/yarn.lock
jest 찍먹 성공... 초기 설정이 너무 헬입니다ㅠㅠ
pr과 다른 내용이지만 저희 이거 빌드파일 ㅋㅋㅋ html 어떻게 안될까요..
> [Test] Jest 초기 설정 및 Auth 관련 테스트 코드 작성

- backend/src/controllers/team-contorller.ts
- backend/src/middlewares/user.ts
- backend/src/routes/team-router.ts
- backend/src/services/team-user-service.ts
- frontend/src/components/Users/UserList/UserList.tsx
> [Fix] middleware 수정

- backend/src/redis/index.ts
원인 : 새로운 postit, message 객체를 생성할 때 index를 증가시키는 코드가 누락됨
해결 : index 증가 코드를 추가함
> [Fix] Redis index 관련 오류 해결

- backend/src/redis/index.ts
- backend/src/services/board-service.ts
- backend/src/services/message-service.ts
기존 : set, get, update, delete
개선 : set, get, CRUD
- promise 기반 -> async, await로 변경했습니다
- 맞게 한건지는 모르겠습니다 하하
> [Refactor] Redis API 리팩토링

- backend/src/controllers/team-contorller.ts
- backend/src/controllers/user-controller.ts
- backend/src/passport/github-strategy.ts
회원가입한 유저는 '놀이터'라는 팀으로부터 자동으로 초대
> [Feat] 놀이터

- backend/src/controllers/schedule-controller.ts
- backend/src/routes/schedule-router.ts
- frontend/src/apis/schedule.ts
- frontend/src/components/Calendar/CalendarHeader/style.ts
- frontend/src/components/Calendar/CalendarModal/index.tsx
- frontend/src/types/calendar.ts
teamId를 각각 query, body로 이동하였습니다.
style 패딩값 살짝 수정했습니다.
> [Fix] 일정 api 수정
